### PR TITLE
Add Slack auto notify on PR opened

### PR DESCRIPTION
**Pull request by sleepylee**
## What happened 👀

Add Slack auto-notify because I'm lazy to remind people 😛 
 
## Proof Of Work 📹
Checking PR status

### CODE REVIEW

**Comment by sleepylee** [comment]
All updated and ready to review @manh-t @markgravity 🙇

**Review by markgravity — APPROVED** [review]
LGTM 🤖

**Review by manh-t — APPROVED** [review]
should we create a channel `#flutter-guild-activity` and notify people when there is comment also? 🥇

**Comment by sleepylee** [comment]
@manh-t for now we don't have to, just notify to the main channel it's ok for this IC process.

**Pull request merged**
